# Check out https://blog.codemagic.io/continuous-integration-and-delivery-for-ionic-apps-codemagic/ for details

workflows:
  # Ionic Capacitor workflows
  ionic-capacitor-ios-app:
    name: Ionic App
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: lts
    scripts:
      - npm install
      - npx cap sync
      - |
        # build iOS
        cd ios
        pod install
        xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
  ionic-capacitor-android-app:
    name: Ionic App
    environment:
      node: lts
    scripts:
      - npm install
      - npx cap sync
      - |
        # build Android
        cd android
        ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
